spring:
  application:
    name: profileService
server:
  port: 8086
logbook:
  format:
    style: http
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoint:
    metrics:
      web:
        exposure:
          include: '*'