spring:
  application:
    name: profileService
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/profileDb}
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD:admin12345}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8086
logbook:
  format:
    style: http
management:
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoint:
    metrics:
      web:
        exposure:
          include: '*'
aws:
  s3:
    bucket:
  secretKey:
  accessKey:
  region: